### ISSUE TITLE
Perfomance Improvements // Profiling

### ISSUE THREAD

**Issue by Miserlou** [binarymax/floodfill.js#11]
Is there anything we can do to improve the performance of this library, perhaps by parallelizing it?

I really like it, but unfortunately it causes an unresponsive script error in Firefox (seems okay in Chrome) - any advice?

**Comment by Miserlou** [comment]
Okay, after a little poking around, it looks like the performance issue is probably in my code, not yours. :)

**Comment by binarymax** [comment]
Hi @Miserlou, would you mind sharing what you did on your end that caused perf issues?  It might help others in the future.  Thanks.

**Comment by Miserlou** [comment]
Turns out that Firefox's (<52) calls to getImageData() are very slow, my application was calling this method a lot when deciding when to floodfill. My (as yet unimplemented) strategy to mitigate this was the call getImageData for a larger area and check the stored bytes instead of calling it for every look up. This seems particularly bad for large, high-dip screens.

Related ticket in Firefox Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1001069

**Comment by binarymax** [comment]
Thanks @Miserlou.  As this is not a floodfill bug, closing this issue.
