### ISSUE TITLE
typeof CanvasRenderingContext2D in iPhone safari is 'object'

### ISSUE THREAD

**Issue by 0x5e** [binarymax/floodfill.js#12]
Hello, when I try to fillFlood, I get this error:
> [Error] TypeError: ctx.fillFlood is not a function. (In 'ctx.fillFlood(offsetX, offsetY, 32)', 'ctx.fillFlood' is undefined)

```
< CanvasRenderingContext2D {webkitLineDash: [], strokeStyle: "#000000", fillStyle: "#000000", globalAlpha: 1, globalCompositeOperation: "source-over", …}
> typeof CanvasRenderingContext2D
< "object"
```

```
if (typeof CanvasRenderingContext2D === 'function') {
	CanvasRenderingContext2D.prototype.fillFlood = fillContext;
};
```

Tested on iPhone6, iOS 9.3.3

**Comment by binarymax** [comment]
Hi @0x5e thanks for the fix!  Very much appreciated.

**Comment by 0x5e** [comment]
@binarymax  thank you too, this project really solved my problem :)
