### ISSUE TITLE
Fill clear?

### ISSUE THREAD

**Issue by tomm1e** [binarymax/floodfill.js#2]
I tried "fill clearing" with a transparent fill color (r:0,g:0,b:0,a:0) and it freezes Chrome, memory goes sky high and the browser needs to be killed.

But if I set the alpha value to 1 it's fine. Is there any way to keep it at 0?

**Comment by binarymax** [comment]
Thanks for letting me know!  Line 37 is the offender.  I should have time to fix it this weekend.

**Comment by binarymax** [comment]
fixed!
