### ISSUE TITLE
Minified version does not work

### ISSUE THREAD

**Issue by dfmiller** [binarymax/floodfill.js#6]
Adding ?min=1 to the tests.html shows that it fails

**Comment by binarymax** [comment]
Thanks for letting me know!  Which browser/version/OS are you using?

**Comment by dfmiller** [comment]
Chrome / Linux

**Comment by binarymax** [comment]
This should work now with v2.  Can you please retest @dfmiller ? Thanks!

**Comment by dfmiller** [comment]
Yes, it works.  (Definitely not backwards compatible)
